### ISSUE TITLE
Build and redeployment

### ISSUE THREAD

**Issue by IllusiveAldebaran** [SuperCompUCSD/SuperCompUCSD.github.io#8]
Setting blog posts prior to when the date had come does not have the posts appear. 
Perhaps a GitHub actions could help.

**Comment by Kwaitv** [comment]
I am having trouble parsing what you mean

**Comment by Kwaitv** [comment]
i understand now i fixed it in commit 73c6c9999ccd5ccbd200fc4445660fab79ae2e87
